version: "2"
linters:
  enable:
    - errname
    - goconst
    - gocyclo
    - nakedret
    - revive
    - unconvert
    - unparam
  settings:
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
