// Code generated by go generate; DO NOT EDIT.
package mock_test

import (
	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/l10n"
)

// generatedRegimes contains all regime country codes from GOBL.
var generatedRegimes = []l10n.TaxCountryCode{
	"AE",
	"AR",
	"AT",
	"BE",
	"BR",
	"CA",
	"CH",
	"CO",
	"DE",
	"DK",
	"EL",
	"ES",
	"FR",
	"GB",
	"IE",
	"IN",
	"IT",
	"MX",
	"NL",
	"PL",
	"PT",
	"SE",
	"SG",
	"US",
}

// generatedAddon maps addon keys to a compatible regime for testing.
type generatedAddon struct {
	Regime l10n.TaxCountryCode
	Key    cbc.Key
}

var generatedAddons = []generatedAddon{
	{"AR", "ar-arca-v4"},
	{"BR", "br-nfe-v4"},
	{"BR", "br-nfse-v1"},
	{"CO", "co-dian-v2"},
	{"DE", "de-xrechnung-v3"},
	{"DE", "de-zugferd-v2"},
	{"ES", "es-facturae-v3"},
	{"ES", "es-sii-v1"},
	{"ES", "es-tbai-v1"},
	{"ES", "es-verifactu-v1"},
	{"DE", "eu-en16931-v2017"},
	{"FR", "fr-choruspro-v1"},
	{"FR", "fr-ctc-flow2-v1"},
	{"FR", "fr-facturx-v1"},
	{"GR", "gr-mydata-v1"},
	{"IT", "it-sdi-v1"},
	{"IT", "it-ticket-v1"},
	{"MX", "mx-cfdi-v4"},
	{"PL", "pl-favat-v3"},
	{"PT", "pt-saft-v1"},
}
