//go:build ignore

// This program generates test data and example invoices from the current
// GOBL regime and addon definitions. Run with: go generate ./...
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"text/template"

	mock "github.com/pablocaeg/gobl.mock"

	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/l10n"
	"github.com/invopop/gobl/tax"

	_ "github.com/invopop/gobl/addons"
	_ "github.com/invopop/gobl/regimes"
)

// addonRegime maps addon keys to compatible regime country codes.
var addonRegime = map[cbc.Key]l10n.TaxCountryCode{
	"ar-arca-v4":       "AR",
	"br-nfe-v4":        "BR",
	"br-nfse-v1":       "BR",
	"co-dian-v2":       "CO",
	"de-xrechnung-v3":  "DE",
	"de-zugferd-v2":    "DE",
	"es-facturae-v3":   "ES",
	"es-sii-v1":        "ES",
	"es-tbai-v1":       "ES",
	"es-verifactu-v1":  "ES",
	"eu-en16931-v2017": "DE",
	"fr-choruspro-v1":  "FR",
	"fr-ctc-flow2-v1":  "FR",
	"fr-facturx-v1":    "FR",
	"gr-mydata-v1":     "GR",
	"it-sdi-v1":        "IT",
	"it-ticket-v1":     "IT",
	"mx-cfdi-v4":       "MX",
	"pl-favat-v3":      "PL",
	"pt-saft-v1":       "PT",
}

func main() {
	if err := generateTestData(); err != nil {
		fmt.Fprintf(os.Stderr, "generating test data: %v\n", err)
		os.Exit(1)
	}
	if err := generateExamples(); err != nil {
		fmt.Fprintf(os.Stderr, "generating examples: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("done")
}

func generateTestData() error {
	regimes := tax.AllRegimeDefs()
	addons := tax.AllAddonDefs()

	codes := make([]string, 0, len(regimes))
	for _, r := range regimes {
		codes = append(codes, string(r.Country))
	}
	sort.Strings(codes)

	type addonEntry struct {
		Regime string
		Key    string
	}
	entries := make([]addonEntry, 0, len(addons))
	for _, ad := range addons {
		regime, ok := addonRegime[ad.Key]
		if !ok {
			// Default: derive country from first 2 chars of addon key.
			prefix := strings.ToUpper(string(ad.Key[:2]))
			regime = l10n.TaxCountryCode(prefix)
		}
		entries = append(entries, addonEntry{
			Regime: string(regime),
			Key:    string(ad.Key),
		})
	}

	tmpl := template.Must(template.New("").Parse(testDataTmpl))
	f, err := os.Create("generated_test.go")
	if err != nil {
		return err
	}
	defer f.Close()

	return tmpl.Execute(f, struct {
		Regimes []string
		Addons  []addonEntry
	}{
		Regimes: codes,
		Addons:  entries,
	})
}

var testDataTmpl = `// Code generated by go generate; DO NOT EDIT.
package mock_test

import (
	"github.com/invopop/gobl/cbc"
	"github.com/invopop/gobl/l10n"
)

// generatedRegimes contains all regime country codes from GOBL.
var generatedRegimes = []l10n.TaxCountryCode{
{{- range .Regimes}}
	"{{.}}",
{{- end}}
}

// generatedAddon maps addon keys to a compatible regime for testing.
type generatedAddon struct {
	Regime l10n.TaxCountryCode
	Key    cbc.Key
}

var generatedAddons = []generatedAddon{
{{- range .Addons}}
	{"{{.Regime}}", "{{.Key}}"},
{{- end}}
}
`

func generateExamples() error {
	examples := []struct {
		name   string
		regime l10n.TaxCountryCode
		addon  cbc.Key
	}{
		{"es-standard", "ES", ""},
		{"de-xrechnung", "DE", "de-xrechnung-v3"},
		{"fr-standard", "FR", ""},
		{"it-sdi", "IT", "it-sdi-v1"},
		{"mx-cfdi", "MX", "mx-cfdi-v4"},
		{"br-nfe", "BR", "br-nfe-v4"},
		{"pt-saft", "PT", "pt-saft-v1"},
		{"us-standard", "US", ""},
	}

	for _, ex := range examples {
		opts := []mock.Option{
			mock.WithRegime(ex.regime),
			mock.WithSeed(42),
		}
		if ex.addon != "" {
			opts = append(opts, mock.WithAddon(ex.addon))
		}

		env, err := mock.Envelope(opts...)
		if err != nil {
			return fmt.Errorf("%s: %w", ex.name, err)
		}

		data, err := json.MarshalIndent(env, "", "  ")
		if err != nil {
			return fmt.Errorf("%s: marshaling: %w", ex.name, err)
		}

		path := fmt.Sprintf("examples/%s.json", ex.name)
		if err := os.WriteFile(path, append(data, '\n'), 0644); err != nil {
			return fmt.Errorf("%s: writing: %w", ex.name, err)
		}
		fmt.Printf("  %s\n", path)
	}
	return nil
}
